// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PensionFund.Infrastructure.EF;

#nullable disable

namespace PensionFund.Infrastructure.EF.Migrations
{
    [DbContext(typeof(PensionFundDbContext))]
    [Migration("20251101230525_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PensionFund")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PensionFund.Domain.Entities.Availability", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "SiteId");

                    b.HasIndex("SiteId");

                    b.ToTable("Availabilities", "PensionFund");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Clients", "PensionFund");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Inscription", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Inscriptions", "PensionFund");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products", "PensionFund");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sites", "PensionFund");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Visit", b =>
                {
                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SiteId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Visits", "PensionFund");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Availability", b =>
                {
                    b.HasOne("PensionFund.Domain.Entities.Product", "Product")
                        .WithMany("Availabilities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PensionFund.Domain.Entities.Site", "Site")
                        .WithMany("Availabilities")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Inscription", b =>
                {
                    b.HasOne("PensionFund.Domain.Entities.Client", "Client")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PensionFund.Domain.Entities.Product", "Product")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Visit", b =>
                {
                    b.HasOne("PensionFund.Domain.Entities.Client", "Client")
                        .WithMany("Visits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PensionFund.Domain.Entities.Site", "Site")
                        .WithMany("Visits")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Client", b =>
                {
                    b.Navigation("Inscriptions");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Product", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("PensionFund.Domain.Entities.Site", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
